"""add gateway_trans_id to payment

Revision ID: 44c8ac08ef37
Revises: 241a95c5d43f
Create Date: 2026-04-22 18:10:45.515102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c8ac08ef37'
down_revision = '241a95c5d43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_trans_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('gateway_trans_id')

    # ### end Alembic commands ###
