"""update enrollment and payment

Revision ID: 507e4d2b05cf
Revises: 807f8dec95f5
Create Date: 2026-04-22 17:04:14.963799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '507e4d2b05cf'
down_revision = '807f8dec95f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_enrollment', ['user_id', 'course_id'])
        batch_op.drop_column('status')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'SUCCESS', 'FAILURE'),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('payments_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('price')
        batch_op.drop_column('enrollment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.create_foreign_key(batch_op.f('payments_ibfk_1'), 'enrollments', ['enrollment_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'SUCCESS', 'FAILURE'),
               nullable=False)
        batch_op.drop_column('total_price')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('unique_enrollment', type_='unique')

    # ### end Alembic commands ###
